name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttihp25b
        with:
          pdk: ihp

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttihp25b
        with:
          pdk: ihp

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttihp25b
        with:
          pdk: ihp

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Viewer Files
        uses: TinyTapeout/tt-gds-action/viewer@ttihp25b
        with:
          pdk: ihp

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "tt/tt_gds_artifacts/tt_viewer"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
